-- ============================================================
-- Valentrax — AUDITORIA DO BANCO (SOMENTE LEITURA — não altera nada)
-- Rode o script INTEIRO no Supabase → SQL Editor.
--
-- Confere: tabelas, colunas, RLS ligado, políticas, funções e trigger de auth.
-- Leia a coluna "situacao". Os problemas (❌) vêm sempre no topo.
--   ❌ FALTANDO      → falta rodar a migração indicada em "origem"
--   ❌ RLS DESLIGADO → tabela exposta: qualquer usuário logado lê tudo
--   ❌ SEM POLÍTICA  → RLS ligado sem regra: a tela fica vazia para todos
--
-- GERADO AUTOMATICAMENTE a partir dos .sql de supabase/ (39 tabelas,
-- 496 colunas). Ao criar uma migração nova, regenere este arquivo
-- para que a auditoria não fique cega ao módulo novo.
-- ============================================================

with
tabelas(nome, origem) as (values
  ('atendimentos','schema'),
  ('auditoria','schema'),
  ('cc_cirurgias','schema'),
  ('cc_salas','schema'),
  ('cid_referencia','schema'),
  ('farm_incompat_y','farmacia-clinica-fase2'),
  ('farm_interacoes','farmacia-clinica-fase2'),
  ('farm_intervencoes','farmacia-intervencoes'),
  ('farm_lotes','farmacia-faseA'),
  ('farm_medicamentos','farmacia-faseA'),
  ('farm_movimentos','farmacia-faseA'),
  ('farm_nao_padronizados','farmacia-nao-padronizados'),
  ('farm_preparo','farmacia-preparo'),
  ('leitos','schema'),
  ('leitos_saidas','schema'),
  ('leitos_turnover','schema'),
  ('pacientes','schema'),
  ('pep_evolucoes','schema'),
  ('profiles','schema'),
  ('ps_administracoes','ps-checagem-medicacao'),
  ('ps_atendimentos','schema'),
  ('ps_prescricao_itens','farmacia-faseB'),
  ('ps_protocolos','ps-salas-censo'),
  ('ps_registros','schema'),
  ('ps_salas','ps-salas'),
  ('ps_sinais','schema'),
  ('scih_casos','schema'),
  ('scih_germes','schema'),
  ('scih_indicadores','schema'),
  ('setores','schema'),
  ('solicitacoes','schema'),
  ('sup_cotacoes','suprimentos-cotacao'),
  ('sup_fornecedores','suprimentos-faseA'),
  ('sup_inventarios','suprimentos-inventario'),
  ('sup_itens','suprimentos-faseA'),
  ('sup_lotes','suprimentos-faseA'),
  ('sup_movimentos','suprimentos-faseA'),
  ('sup_pedidos','suprimentos-faseC'),
  ('sup_requisicoes','suprimentos-faseB')
),
colunas(tabela, coluna, origem) as (values
  ('atendimentos','created_at','schema'),
  ('atendimentos','data','schema'),
  ('atendimentos','emergencias','schema'),
  ('atendimentos','especialidade','schema'),
  ('atendimentos','faltas','schema'),
  ('atendimentos','id','schema'),
  ('atendimentos','livres','schema'),
  ('atendimentos','ofertadas','schema'),
  ('atendimentos','primeiras','schema'),
  ('atendimentos','realizadas','schema'),
  ('atendimentos','retornos','schema'),
  ('atendimentos','usuario','schema'),
  ('auditoria','acao','schema'),
  ('auditoria','alvo','schema'),
  ('auditoria','id','schema'),
  ('auditoria','ts','schema'),
  ('auditoria','usuario','schema'),
  ('cc_cirurgias','anestesista','schema'),
  ('cc_cirurgias','cancelamento_motivo','schema'),
  ('cc_cirurgias','checkin_em','schema'),
  ('cc_cirurgias','chk_sign_in','schema'),
  ('cc_cirurgias','chk_sign_out','schema'),
  ('cc_cirurgias','chk_time_out','schema'),
  ('cc_cirurgias','cirurgiao','schema'),
  ('cc_cirurgias','data','schema'),
  ('cc_cirurgias','duracao_prev_min','schema'),
  ('cc_cirurgias','entrada_sala_em','schema'),
  ('cc_cirurgias','fim_cirurgia_em','schema'),
  ('cc_cirurgias','hora_prevista','schema'),
  ('cc_cirurgias','id','schema'),
  ('cc_cirurgias','iniciais','schema'),
  ('cc_cirurgias','inicio_anestesia_em','schema'),
  ('cc_cirurgias','inicio_cirurgia_em','schema'),
  ('cc_cirurgias','observacao','schema'),
  ('cc_cirurgias','opme','schema'),
  ('cc_cirurgias','procedimento','schema'),
  ('cc_cirurgias','prontuario','schema'),
  ('cc_cirurgias','rpa_entrada_em','schema'),
  ('cc_cirurgias','rpa_saida_em','schema'),
  ('cc_cirurgias','saida_sala_em','schema'),
  ('cc_cirurgias','sala','schema'),
  ('cc_cirurgias','status','schema'),
  ('cc_cirurgias','tipo_anestesia','schema'),
  ('cc_cirurgias','updated_at','schema'),
  ('cc_cirurgias','usuario','schema'),
  ('cc_salas','ativa','schema'),
  ('cc_salas','nome','schema'),
  ('cc_salas','ordem','schema'),
  ('cc_salas','updated_at','schema'),
  ('cc_salas','usuario','schema'),
  ('cid_referencia','cid','schema'),
  ('cid_referencia','descricao','schema'),
  ('cid_referencia','dias','schema'),
  ('cid_referencia','tratamento','schema'),
  ('cid_referencia','updated_at','schema'),
  ('cid_referencia','usuario','schema'),
  ('farm_incompat_y','created_at','farmacia-clinica-fase2'),
  ('farm_incompat_y','descricao','farmacia-clinica-fase2'),
  ('farm_incompat_y','id','farmacia-clinica-fase2'),
  ('farm_incompat_y','substancia_a','farmacia-clinica-fase2'),
  ('farm_incompat_y','substancia_b','farmacia-clinica-fase2'),
  ('farm_incompat_y','updated_at','farmacia-clinica-fase2'),
  ('farm_incompat_y','usuario','farmacia-clinica-fase2'),
  ('farm_interacoes','conduta','farmacia-clinica-fase2'),
  ('farm_interacoes','created_at','farmacia-clinica-fase2'),
  ('farm_interacoes','descricao','farmacia-clinica-fase2'),
  ('farm_interacoes','gravidade','farmacia-clinica-fase2'),
  ('farm_interacoes','id','farmacia-clinica-fase2'),
  ('farm_interacoes','substancia_a','farmacia-clinica-fase2'),
  ('farm_interacoes','substancia_b','farmacia-clinica-fase2'),
  ('farm_interacoes','updated_at','farmacia-clinica-fase2'),
  ('farm_interacoes','usuario','farmacia-clinica-fase2'),
  ('farm_intervencoes','atendimento_id','farmacia-intervencoes'),
  ('farm_intervencoes','conduta','farmacia-intervencoes'),
  ('farm_intervencoes','created_at','farmacia-intervencoes'),
  ('farm_intervencoes','desfecho','farmacia-intervencoes'),
  ('farm_intervencoes','farmaceutico','farmacia-intervencoes'),
  ('farm_intervencoes','gravidade','farmacia-intervencoes'),
  ('farm_intervencoes','id','farmacia-intervencoes'),
  ('farm_intervencoes','medicamento_nome','farmacia-intervencoes'),
  ('farm_intervencoes','paciente_iniciais','farmacia-intervencoes'),
  ('farm_intervencoes','paciente_prontuario','farmacia-intervencoes'),
  ('farm_intervencoes','prescricao_item_id','farmacia-intervencoes'),
  ('farm_intervencoes','problema','farmacia-intervencoes'),
  ('farm_intervencoes','status','farmacia-intervencoes'),
  ('farm_intervencoes','tipo','farmacia-intervencoes'),
  ('farm_intervencoes','updated_at','farmacia-intervencoes'),
  ('farm_intervencoes','usuario','farmacia-intervencoes'),
  ('farm_lotes','id','farmacia-faseA'),
  ('farm_lotes','lote','farmacia-faseA'),
  ('farm_lotes','medicamento_id','farmacia-faseA'),
  ('farm_lotes','quantidade','farmacia-faseA'),
  ('farm_lotes','updated_at','farmacia-faseA'),
  ('farm_lotes','validade','farmacia-faseA'),
  ('farm_medicamentos','ajuste_hepatico','farmacia-clinica-fase1'),
  ('farm_medicamentos','ajuste_renal','farmacia-clinica-fase1'),
  ('farm_medicamentos','ativo','farmacia-faseA'),
  ('farm_medicamentos','classe','farmacia-seed'),
  ('farm_medicamentos','concentracao','farmacia-faseA'),
  ('farm_medicamentos','controlado','farmacia-faseA'),
  ('farm_medicamentos','created_at','farmacia-faseA'),
  ('farm_medicamentos','custo_unitario','farmacia-custos'),
  ('farm_medicamentos','dose_maxima_dia','farmacia-clinica-fase1'),
  ('farm_medicamentos','dose_maxima_unid','farmacia-clinica-fase1'),
  ('farm_medicamentos','duracao_maxima_dias','farmacia-clinica-fase1'),
  ('farm_medicamentos','estoque_minimo','farmacia-faseA'),
  ('farm_medicamentos','forma','farmacia-faseA'),
  ('farm_medicamentos','grupo_terapeutico','farmacia-clinica-fase1'),
  ('farm_medicamentos','id','farmacia-faseA'),
  ('farm_medicamentos','idade_pediatrica','farmacia-clinica-fase1'),
  ('farm_medicamentos','inapropriado_idoso','farmacia-clinica-fase1'),
  ('farm_medicamentos','inapropriado_pediatrico','farmacia-clinica-fase1'),
  ('farm_medicamentos','motivo_idoso','farmacia-clinica-fase1'),
  ('farm_medicamentos','motivo_pediatrico','farmacia-clinica-fase1'),
  ('farm_medicamentos','nao_triturar','farmacia-clinica-fase1'),
  ('farm_medicamentos','nome','farmacia-faseA'),
  ('farm_medicamentos','obs_clinica','farmacia-clinica-fase1'),
  ('farm_medicamentos','observacao','farmacia-faseA'),
  ('farm_medicamentos','principio_ativo','farmacia-faseA'),
  ('farm_medicamentos','unidade','farmacia-faseA'),
  ('farm_medicamentos','updated_at','farmacia-faseA'),
  ('farm_medicamentos','usuario','farmacia-faseA'),
  ('farm_movimentos','atendimento_id','farmacia-faseB'),
  ('farm_movimentos','created_at','farmacia-faseA'),
  ('farm_movimentos','custo_unit','suprimentos-inventario'),
  ('farm_movimentos','documento','farmacia-faseA'),
  ('farm_movimentos','id','farmacia-faseA'),
  ('farm_movimentos','lote','farmacia-faseA'),
  ('farm_movimentos','lote_id','farmacia-faseA'),
  ('farm_movimentos','medicamento_id','farmacia-faseA'),
  ('farm_movimentos','motivo','farmacia-faseA'),
  ('farm_movimentos','paciente_iniciais','farmacia-faseA'),
  ('farm_movimentos','paciente_prontuario','farmacia-faseA'),
  ('farm_movimentos','prescricao_item_id','farmacia-faseB'),
  ('farm_movimentos','quantidade','farmacia-faseA'),
  ('farm_movimentos','setor','farmacia-faseB'),
  ('farm_movimentos','tipo','farmacia-faseA'),
  ('farm_movimentos','usuario','farmacia-faseA'),
  ('farm_movimentos','validade','farmacia-faseA'),
  ('farm_nao_padronizados','apresentacao','farmacia-nao-padronizados'),
  ('farm_nao_padronizados','conferido','farmacia-nao-padronizados'),
  ('farm_nao_padronizados','created_at','farmacia-nao-padronizados'),
  ('farm_nao_padronizados','id','farmacia-nao-padronizados'),
  ('farm_nao_padronizados','lote','farmacia-nao-padronizados'),
  ('farm_nao_padronizados','medicamento','farmacia-nao-padronizados'),
  ('farm_nao_padronizados','observacao','farmacia-nao-padronizados'),
  ('farm_nao_padronizados','origem','farmacia-nao-padronizados'),
  ('farm_nao_padronizados','paciente_iniciais','farmacia-nao-padronizados'),
  ('farm_nao_padronizados','paciente_prontuario','farmacia-nao-padronizados'),
  ('farm_nao_padronizados','quantidade','farmacia-nao-padronizados'),
  ('farm_nao_padronizados','setor','farmacia-nao-padronizados'),
  ('farm_nao_padronizados','status','farmacia-nao-padronizados'),
  ('farm_nao_padronizados','unidade','farmacia-nao-padronizados'),
  ('farm_nao_padronizados','updated_at','farmacia-nao-padronizados'),
  ('farm_nao_padronizados','usuario','farmacia-nao-padronizados'),
  ('farm_nao_padronizados','validade','farmacia-nao-padronizados'),
  ('farm_preparo','atendimento_id','farmacia-preparo'),
  ('farm_preparo','created_at','farmacia-preparo'),
  ('farm_preparo','id','farmacia-preparo'),
  ('farm_preparo','observacao','farmacia-preparo'),
  ('farm_preparo','pronto_em','farmacia-preparo'),
  ('farm_preparo','pronto_por','farmacia-preparo'),
  ('farm_preparo','recebido_em','farmacia-preparo'),
  ('farm_preparo','recebido_por','farmacia-preparo'),
  ('farm_preparo','registro_id','farmacia-preparo'),
  ('farm_preparo','retirado_em','farmacia-preparo'),
  ('farm_preparo','retirado_por','farmacia-preparo'),
  ('farm_preparo','status','farmacia-preparo'),
  ('farm_preparo','updated_at','farmacia-preparo'),
  ('farm_preparo','usuario','farmacia-preparo'),
  ('leitos_saidas','cid','schema'),
  ('leitos_saidas','created_at','schema'),
  ('leitos_saidas','data_alta','schema'),
  ('leitos_saidas','data_internacao','schema'),
  ('leitos_saidas','desfecho','schema'),
  ('leitos_saidas','dias_permanencia','schema'),
  ('leitos_saidas','disp_em','schema'),
  ('leitos_saidas','id','schema'),
  ('leitos_saidas','iniciais','schema'),
  ('leitos_saidas','leito','schema'),
  ('leitos_saidas','motivo','schema'),
  ('leitos_saidas','prontuario','schema'),
  ('leitos_saidas','setor','leitos-saida-setor'),
  ('leitos_saidas','usuario','schema'),
  ('leitos_turnover','created_at','schema'),
  ('leitos_turnover','disp_em','schema'),
  ('leitos_turnover','entrada_em','schema'),
  ('leitos_turnover','id','schema'),
  ('leitos_turnover','leito','schema'),
  ('leitos_turnover','pronto_em','schema'),
  ('leitos_turnover','solic_em','schema'),
  ('leitos_turnover','usuario','schema'),
  ('leitos','alta_pendencias','leitos-kanban-metas'),
  ('leitos','alta_periodo','leitos-kanban-metas'),
  ('leitos','cid','schema'),
  ('leitos','data_internacao','schema'),
  ('leitos','dias_previstos','schema'),
  ('leitos','disp_em','schema'),
  ('leitos','entrada_em','schema'),
  ('leitos','identificacao','schema'),
  ('leitos','iniciais','schema'),
  ('leitos','interdicao_motivo','schema'),
  ('leitos','isolamento','schema'),
  ('leitos','motivo','schema'),
  ('leitos','pronto_em','schema'),
  ('leitos','prontuario','schema'),
  ('leitos','ps_atendimento_id','ps-origem-elo'),
  ('leitos','setor','schema'),
  ('leitos','solic_em','schema'),
  ('leitos','status','schema'),
  ('leitos','updated_at','schema'),
  ('leitos','usuario','schema'),
  ('pacientes','ano_nascimento','schema'),
  ('pacientes','iniciais','schema'),
  ('pacientes','prontuario','schema'),
  ('pacientes','sexo','schema'),
  ('pacientes','updated_at','schema'),
  ('pacientes','usuario','schema'),
  ('pep_evolucoes','criado_em','schema'),
  ('pep_evolucoes','id','schema'),
  ('pep_evolucoes','prontuario','schema'),
  ('pep_evolucoes','texto','schema'),
  ('pep_evolucoes','tipo','schema'),
  ('pep_evolucoes','usuario','schema'),
  ('profiles','created_at','schema'),
  ('profiles','id','schema'),
  ('profiles','nome','schema'),
  ('profiles','role','schema'),
  ('profiles','username','schema'),
  ('ps_administracoes','administrado_em','ps-checagem-medicacao'),
  ('ps_administracoes','atendimento_id','ps-checagem-medicacao'),
  ('ps_administracoes','categoria','ps-checagem-medicacao'),
  ('ps_administracoes','criado_em','ps-checagem-medicacao'),
  ('ps_administracoes','dose','ps-checagem-medicacao'),
  ('ps_administracoes','id','ps-checagem-medicacao'),
  ('ps_administracoes','medicamento_id','ps-checagem-medicacao'),
  ('ps_administracoes','medicamento_nome','ps-checagem-medicacao'),
  ('ps_administracoes','motivo','ps-checagem-medicacao'),
  ('ps_administracoes','observacao','ps-checagem-medicacao'),
  ('ps_administracoes','prescricao_item_id','ps-checagem-medicacao'),
  ('ps_administracoes','status','ps-checagem-medicacao'),
  ('ps_administracoes','usuario','ps-checagem-medicacao'),
  ('ps_administracoes','via','ps-checagem-medicacao'),
  ('ps_atendimentos','alergias','farmacia-clinica-fase1'),
  ('ps_atendimentos','atendimento_em','schema'),
  ('ps_atendimentos','chegada_em','schema'),
  ('ps_atendimentos','classificacao','schema'),
  ('ps_atendimentos','clearance_renal','farmacia-clinica-fase1'),
  ('ps_atendimentos','consciencia','schema'),
  ('ps_atendimentos','desfecho','schema'),
  ('ps_atendimentos','desfecho_em','schema'),
  ('ps_atendimentos','dor','schema'),
  ('ps_atendimentos','em_sonda','farmacia-clinica-fase1'),
  ('ps_atendimentos','fc','schema'),
  ('ps_atendimentos','fr','schema'),
  ('ps_atendimentos','funcao_hepatica','farmacia-clinica-fase1'),
  ('ps_atendimentos','gestante','farmacia-clinica-fase1'),
  ('ps_atendimentos','glicemia','schema'),
  ('ps_atendimentos','id','schema'),
  ('ps_atendimentos','idade','farmacia-clinica-fase1'),
  ('ps_atendimentos','iniciais','schema'),
  ('ps_atendimentos','medico','schema'),
  ('ps_atendimentos','observacao','schema'),
  ('ps_atendimentos','origem','ps-origem-elo'),
  ('ps_atendimentos','origem_detalhe','ps-origem-elo'),
  ('ps_atendimentos','pa_diast','schema'),
  ('ps_atendimentos','pa_sist','schema'),
  ('ps_atendimentos','peso','farmacia-clinica-fase1'),
  ('ps_atendimentos','prontuario','schema'),
  ('ps_atendimentos','queixa','schema'),
  ('ps_atendimentos','setor_destino','schema'),
  ('ps_atendimentos','spo2','schema'),
  ('ps_atendimentos','status','schema'),
  ('ps_atendimentos','temp','schema'),
  ('ps_atendimentos','triagem_em','schema'),
  ('ps_atendimentos','updated_at','schema'),
  ('ps_atendimentos','usuario','schema'),
  ('ps_prescricao_itens','atendimento_id','farmacia-faseB'),
  ('ps_prescricao_itens','created_at','farmacia-faseB'),
  ('ps_prescricao_itens','dose','farmacia-faseB'),
  ('ps_prescricao_itens','dose_unidade','farmacia-clinica-fase1'),
  ('ps_prescricao_itens','dose_valor','farmacia-clinica-fase1'),
  ('ps_prescricao_itens','duracao_dias','farmacia-clinica-fase1'),
  ('ps_prescricao_itens','frequencia_dia','farmacia-clinica-fase1'),
  ('ps_prescricao_itens','id','farmacia-faseB'),
  ('ps_prescricao_itens','medicamento_id','farmacia-faseB'),
  ('ps_prescricao_itens','medicamento_nome','farmacia-faseB'),
  ('ps_prescricao_itens','quantidade','farmacia-faseB'),
  ('ps_prescricao_itens','registro_id','farmacia-faseB'),
  ('ps_prescricao_itens','unidade','farmacia-faseB'),
  ('ps_prescricao_itens','usuario','farmacia-faseB'),
  ('ps_prescricao_itens','via','farmacia-faseB'),
  ('ps_protocolos','ativo','ps-salas-censo'),
  ('ps_protocolos','categoria','ps-salas-censo'),
  ('ps_protocolos','conteudo','ps-salas-censo'),
  ('ps_protocolos','created_at','ps-salas-censo'),
  ('ps_protocolos','id','ps-salas-censo'),
  ('ps_protocolos','referencia','ps-salas-censo'),
  ('ps_protocolos','resumo','ps-salas-censo'),
  ('ps_protocolos','titulo','ps-salas-censo'),
  ('ps_protocolos','updated_at','ps-salas-censo'),
  ('ps_protocolos','usuario','ps-salas-censo'),
  ('ps_registros','atendimento_id','schema'),
  ('ps_registros','categoria','schema'),
  ('ps_registros','criado_em','schema'),
  ('ps_registros','id','schema'),
  ('ps_registros','resultado','schema'),
  ('ps_registros','resultado_em','schema'),
  ('ps_registros','status','schema'),
  ('ps_registros','texto','schema'),
  ('ps_registros','tipo','schema'),
  ('ps_registros','usuario','schema'),
  ('ps_salas','area','ps-salas'),
  ('ps_salas','atendimento_id','ps-salas'),
  ('ps_salas','ativo','ps-salas'),
  ('ps_salas','conta_censo','ps-salas-censo'),
  ('ps_salas','created_at','ps-salas'),
  ('ps_salas','id','ps-salas'),
  ('ps_salas','identificacao','ps-salas'),
  ('ps_salas','observacao','ps-salas'),
  ('ps_salas','ocupado_em','ps-salas'),
  ('ps_salas','ordem','ps-salas'),
  ('ps_salas','status','ps-salas'),
  ('ps_salas','updated_at','ps-salas'),
  ('ps_salas','usuario','ps-salas'),
  ('ps_sinais','aferido_em','schema'),
  ('ps_sinais','atendimento_id','schema'),
  ('ps_sinais','classificacao_escolhida','schema'),
  ('ps_sinais','classificacao_sugerida','schema'),
  ('ps_sinais','consciencia','schema'),
  ('ps_sinais','dor','schema'),
  ('ps_sinais','fc','schema'),
  ('ps_sinais','fr','schema'),
  ('ps_sinais','glicemia','schema'),
  ('ps_sinais','id','schema'),
  ('ps_sinais','pa_diast','schema'),
  ('ps_sinais','pa_sist','schema'),
  ('ps_sinais','spo2','schema'),
  ('ps_sinais','temp','schema'),
  ('ps_sinais','usuario','schema'),
  ('scih_casos','antibiotico','schema'),
  ('scih_casos','created_at','schema'),
  ('scih_casos','data_coleta','schema'),
  ('scih_casos','data_resultado','schema'),
  ('scih_casos','dias_antibiotico','schema'),
  ('scih_casos','germe','schema'),
  ('scih_casos','id','schema'),
  ('scih_casos','iniciais','schema'),
  ('scih_casos','isolamento','schema'),
  ('scih_casos','leito','schema'),
  ('scih_casos','multirresistente','schema'),
  ('scih_casos','observacao','schema'),
  ('scih_casos','prontuario','schema'),
  ('scih_casos','status','schema'),
  ('scih_casos','updated_at','schema'),
  ('scih_casos','usuario','schema'),
  ('scih_germes','embasamento','schema'),
  ('scih_germes','isolamento','schema'),
  ('scih_germes','nome','schema'),
  ('scih_germes','observacao','schema'),
  ('scih_germes','tipo','schema'),
  ('scih_germes','updated_at','schema'),
  ('scih_germes','usuario','schema'),
  ('scih_indicadores','antimicrobiano_dot','schema'),
  ('scih_indicadores','cir_artroplastia','schema'),
  ('scih_indicadores','cir_cesariana','schema'),
  ('scih_indicadores','cir_oftalmo','schema'),
  ('scih_indicadores','competencia','schema'),
  ('scih_indicadores','culturas_coletadas','schema'),
  ('scih_indicadores','culturas_positivas','schema'),
  ('scih_indicadores','exames_imagem','schema'),
  ('scih_indicadores','exames_lab','schema'),
  ('scih_indicadores','higiene_oportunidades','schema'),
  ('scih_indicadores','higiene_realizadas','schema'),
  ('scih_indicadores','isc_artroplastia','schema'),
  ('scih_indicadores','isc_cesariana','schema'),
  ('scih_indicadores','isc_oftalmo','schema'),
  ('scih_indicadores','observacao','schema'),
  ('scih_indicadores','pacientes_dia','schema'),
  ('scih_indicadores','pav_casos','schema'),
  ('scih_indicadores','treinamentos','schema'),
  ('scih_indicadores','treinamentos_participantes','schema'),
  ('scih_indicadores','updated_at','schema'),
  ('scih_indicadores','usuario','schema'),
  ('scih_indicadores','ventilador_dia','schema'),
  ('setores','alerta_amarelo','schema'),
  ('setores','alerta_vermelho','schema'),
  ('setores','meta_giro','leitos-kanban-metas'),
  ('setores','meta_ocupacao','leitos-kanban-metas'),
  ('setores','meta_permanencia','leitos-kanban-metas'),
  ('setores','nome','schema'),
  ('setores','ordem','schema'),
  ('setores','updated_at','schema'),
  ('setores','usuario','schema'),
  ('solicitacoes','created_at','schema'),
  ('solicitacoes','hora_pedido','schema'),
  ('solicitacoes','id','schema'),
  ('solicitacoes','iniciais','schema'),
  ('solicitacoes','motivo_espera','leitos-kanban-metas'),
  ('solicitacoes','ps_atendimento_id','ps-origem-elo'),
  ('solicitacoes','setor_destino','schema'),
  ('solicitacoes','setor_origem','schema'),
  ('solicitacoes','status','schema'),
  ('solicitacoes','usuario','schema'),
  ('sup_cotacoes','created_at','suprimentos-cotacao'),
  ('sup_cotacoes','descricao','suprimentos-cotacao'),
  ('sup_cotacoes','fornecedores','suprimentos-cotacao'),
  ('sup_cotacoes','id','suprimentos-cotacao'),
  ('sup_cotacoes','itens','suprimentos-cotacao'),
  ('sup_cotacoes','observacao','suprimentos-cotacao'),
  ('sup_cotacoes','status','suprimentos-cotacao'),
  ('sup_cotacoes','updated_at','suprimentos-cotacao'),
  ('sup_cotacoes','usuario','suprimentos-cotacao'),
  ('sup_fornecedores','ativo','suprimentos-faseA'),
  ('sup_fornecedores','categorias','suprimentos-faseA'),
  ('sup_fornecedores','cnpj','suprimentos-faseA'),
  ('sup_fornecedores','contato','suprimentos-faseA'),
  ('sup_fornecedores','created_at','suprimentos-faseA'),
  ('sup_fornecedores','email','suprimentos-faseA'),
  ('sup_fornecedores','id','suprimentos-faseA'),
  ('sup_fornecedores','lead_time_dias','suprimentos-ponto-de-pedido'),
  ('sup_fornecedores','nome','suprimentos-faseA'),
  ('sup_fornecedores','observacao','suprimentos-faseA'),
  ('sup_fornecedores','telefone','suprimentos-faseA'),
  ('sup_fornecedores','updated_at','suprimentos-faseA'),
  ('sup_fornecedores','usuario','suprimentos-faseA'),
  ('sup_inventarios','ajustado','suprimentos-inventario'),
  ('sup_inventarios','contado','suprimentos-inventario'),
  ('sup_inventarios','created_at','suprimentos-inventario'),
  ('sup_inventarios','diferenca','suprimentos-inventario'),
  ('sup_inventarios','id','suprimentos-inventario'),
  ('sup_inventarios','item_id','suprimentos-inventario'),
  ('sup_inventarios','observacao','suprimentos-inventario'),
  ('sup_inventarios','saldo_sistema','suprimentos-inventario'),
  ('sup_inventarios','usuario','suprimentos-inventario'),
  ('sup_itens','ativo','suprimentos-faseA'),
  ('sup_itens','categoria','suprimentos-faseA'),
  ('sup_itens','codigo_barras','suprimentos-inventario'),
  ('sup_itens','created_at','suprimentos-faseA'),
  ('sup_itens','custo_unitario','suprimentos-faseA'),
  ('sup_itens','estoque_minimo','suprimentos-faseA'),
  ('sup_itens','id','suprimentos-faseA'),
  ('sup_itens','nome','suprimentos-faseA'),
  ('sup_itens','observacao','suprimentos-faseA'),
  ('sup_itens','unidade','suprimentos-faseA'),
  ('sup_itens','updated_at','suprimentos-faseA'),
  ('sup_itens','usuario','suprimentos-faseA'),
  ('sup_lotes','id','suprimentos-faseA'),
  ('sup_lotes','item_id','suprimentos-faseA'),
  ('sup_lotes','lote','suprimentos-faseA'),
  ('sup_lotes','quantidade','suprimentos-faseA'),
  ('sup_lotes','updated_at','suprimentos-faseA'),
  ('sup_lotes','validade','suprimentos-faseA'),
  ('sup_movimentos','created_at','suprimentos-faseA'),
  ('sup_movimentos','custo_unit','suprimentos-inventario'),
  ('sup_movimentos','documento','suprimentos-faseA'),
  ('sup_movimentos','fornecedor_id','suprimentos-faseA'),
  ('sup_movimentos','id','suprimentos-faseA'),
  ('sup_movimentos','item_id','suprimentos-faseA'),
  ('sup_movimentos','lote','suprimentos-faseA'),
  ('sup_movimentos','lote_id','suprimentos-faseA'),
  ('sup_movimentos','motivo','suprimentos-faseA'),
  ('sup_movimentos','quantidade','suprimentos-faseA'),
  ('sup_movimentos','setor','suprimentos-faseA'),
  ('sup_movimentos','tipo','suprimentos-faseA'),
  ('sup_movimentos','usuario','suprimentos-faseA'),
  ('sup_movimentos','validade','suprimentos-faseA'),
  ('sup_pedidos','created_at','suprimentos-faseC'),
  ('sup_pedidos','enviado_em','suprimentos-faseC'),
  ('sup_pedidos','enviado_por','suprimentos-faseC'),
  ('sup_pedidos','fornecedor_id','suprimentos-faseC'),
  ('sup_pedidos','fornecedor_nome','suprimentos-faseC'),
  ('sup_pedidos','id','suprimentos-faseC'),
  ('sup_pedidos','itens','suprimentos-faseC'),
  ('sup_pedidos','observacao','suprimentos-faseC'),
  ('sup_pedidos','previsao_entrega','suprimentos-faseC'),
  ('sup_pedidos','recebido_em','suprimentos-faseC'),
  ('sup_pedidos','recebido_por','suprimentos-faseC'),
  ('sup_pedidos','status','suprimentos-faseC'),
  ('sup_pedidos','updated_at','suprimentos-faseC'),
  ('sup_pedidos','usuario','suprimentos-faseC'),
  ('sup_requisicoes','created_at','suprimentos-faseB'),
  ('sup_requisicoes','entregue_em','suprimentos-faseB'),
  ('sup_requisicoes','entregue_por','suprimentos-faseB'),
  ('sup_requisicoes','id','suprimentos-faseB'),
  ('sup_requisicoes','itens','suprimentos-faseB'),
  ('sup_requisicoes','observacao','suprimentos-faseB'),
  ('sup_requisicoes','pronto_em','suprimentos-faseB'),
  ('sup_requisicoes','pronto_por','suprimentos-faseB'),
  ('sup_requisicoes','recebido_em','suprimentos-faseB'),
  ('sup_requisicoes','recebido_por','suprimentos-faseB'),
  ('sup_requisicoes','setor','suprimentos-faseB'),
  ('sup_requisicoes','solicitado_por','suprimentos-faseB'),
  ('sup_requisicoes','status','suprimentos-faseB'),
  ('sup_requisicoes','updated_at','suprimentos-faseB'),
  ('sup_requisicoes','usuario','suprimentos-faseB')
),
funcoes(nome) as (values ('my_role'), ('handle_new_user')),

chk_tab as (
  select 0 as ord, 'TABELA' as categoria, t.nome as item, t.origem as origem,
    case when it.table_name is null then '❌ FALTANDO' else '✅ ok' end as situacao,
    case when it.table_name is null then 1 else 0 end as prob
  from tabelas t
  left join information_schema.tables it
    on it.table_schema='public' and it.table_name=t.nome
),
chk_col as (
  select 1, 'COLUNA', c.tabela||'.'||c.coluna, c.origem,
    case when ic.column_name is null then '❌ FALTANDO' else '✅ ok' end,
    case when ic.column_name is null then 1 else 0 end
  from colunas c
  left join information_schema.columns ic
    on ic.table_schema='public' and ic.table_name=c.tabela and ic.column_name=c.coluna
),
chk_rls as (
  select 2, 'RLS (segurança)', t.nome, t.origem,
    case when cl.relrowsecurity then '✅ ativo' else '❌ RLS DESLIGADO' end,
    case when cl.relrowsecurity then 0 else 1 end
  from tabelas t
  join pg_class cl on cl.relname=t.nome
  join pg_namespace ns on ns.oid=cl.relnamespace and ns.nspname='public'
),
-- RLS ligado SEM nenhuma política bloqueia todo mundo: a tela fica vazia
-- e o app não mostra erro nenhum. É o defeito mais difícil de perceber.
chk_pol as (
  select 3, 'POLÍTICAS', t.nome, t.origem,
    case when count(p.polname)=0 then '❌ SEM POLÍTICA'
         else '✅ '||count(p.polname)||' política(s)' end,
    case when count(p.polname)=0 then 1 else 0 end
  from tabelas t
  join pg_class cl on cl.relname=t.nome
  join pg_namespace ns on ns.oid=cl.relnamespace and ns.nspname='public'
  left join pg_policy p on p.polrelid=cl.oid
  group by t.nome, t.origem
),
chk_fn as (
  select 4, 'FUNÇÃO', f.nome, 'auth/permissões',
    case when p.proname is null then '❌ FALTANDO' else '✅ ok' end,
    case when p.proname is null then 1 else 0 end
  from funcoes f
  left join pg_proc p on p.proname=f.nome
  left join pg_namespace n on n.oid=p.pronamespace and n.nspname='public'
),
chk_trg as (
  select 5, 'TRIGGER', 'on_auth_user_created', 'criação de perfil no login',
    case when count(*)=0 then '❌ FALTANDO' else '✅ ok' end,
    case when count(*)=0 then 1 else 0 end
  from pg_trigger where tgname='on_auth_user_created'
),
tudo as (
  select * from chk_tab union all select * from chk_col union all
  select * from chk_rls union all select * from chk_pol union all
  select * from chk_fn  union all select * from chk_trg
)
select categoria, item, situacao, origem
from tudo
order by prob desc, ord, item;
