-- ═══════════════════════════════════════════════════════════
-- SUPRIMENTOS — Seed do catálogo (~120 materiais comuns de hospital)
-- Só catálogo (sem estoque). Insere apenas os que ainda NÃO existem
-- (comparação pelo nome) — seguro rodar de novo. Revisar com a equipe.
-- ═══════════════════════════════════════════════════════════
insert into public.sup_itens (nome, categoria, unidade)
select v.nome, v.categoria, v.unidade from (values
  -- Material médico-hospitalar
  ('Luva de procedimento P — caixa 100',            'Material médico-hospitalar', 'caixa'),
  ('Luva de procedimento M — caixa 100',            'Material médico-hospitalar', 'caixa'),
  ('Luva de procedimento G — caixa 100',            'Material médico-hospitalar', 'caixa'),
  ('Luva cirúrgica estéril 7,0 — par',              'Material médico-hospitalar', 'par'),
  ('Luva cirúrgica estéril 7,5 — par',              'Material médico-hospitalar', 'par'),
  ('Luva cirúrgica estéril 8,0 — par',              'Material médico-hospitalar', 'par'),
  ('Seringa 1 mL (insulina)',                       'Material médico-hospitalar', 'unidade'),
  ('Seringa 3 mL',                                  'Material médico-hospitalar', 'unidade'),
  ('Seringa 5 mL',                                  'Material médico-hospitalar', 'unidade'),
  ('Seringa 10 mL',                                 'Material médico-hospitalar', 'unidade'),
  ('Seringa 20 mL',                                 'Material médico-hospitalar', 'unidade'),
  ('Agulha 25x7',                                   'Material médico-hospitalar', 'unidade'),
  ('Agulha 25x8',                                   'Material médico-hospitalar', 'unidade'),
  ('Agulha 40x12',                                  'Material médico-hospitalar', 'unidade'),
  ('Scalp nº 21',                                   'Material médico-hospitalar', 'unidade'),
  ('Scalp nº 23',                                   'Material médico-hospitalar', 'unidade'),
  ('Cateter intravenoso nº 18',                     'Material médico-hospitalar', 'unidade'),
  ('Cateter intravenoso nº 20',                     'Material médico-hospitalar', 'unidade'),
  ('Cateter intravenoso nº 22',                     'Material médico-hospitalar', 'unidade'),
  ('Cateter intravenoso nº 24',                     'Material médico-hospitalar', 'unidade'),
  ('Equipo macrogotas',                             'Material médico-hospitalar', 'unidade'),
  ('Equipo microgotas',                             'Material médico-hospitalar', 'unidade'),
  ('Equipo para bomba de infusão',                  'Material médico-hospitalar', 'unidade'),
  ('Torneirinha 3 vias',                            'Material médico-hospitalar', 'unidade'),
  ('Extensor / polifix 2 vias',                     'Material médico-hospitalar', 'unidade'),
  ('Sonda Foley nº 14',                             'Material médico-hospitalar', 'unidade'),
  ('Sonda Foley nº 16',                             'Material médico-hospitalar', 'unidade'),
  ('Sonda Foley nº 18',                             'Material médico-hospitalar', 'unidade'),
  ('Sonda uretral nº 10',                           'Material médico-hospitalar', 'unidade'),
  ('Sonda uretral nº 12',                           'Material médico-hospitalar', 'unidade'),
  ('Sonda nasogástrica nº 14',                      'Material médico-hospitalar', 'unidade'),
  ('Sonda nasogástrica nº 16',                      'Material médico-hospitalar', 'unidade'),
  ('Coletor de urina sistema fechado',              'Material médico-hospitalar', 'unidade'),
  ('Coletor de urina sistema aberto',               'Material médico-hospitalar', 'unidade'),
  ('Atadura de crepom 10 cm',                       'Material médico-hospitalar', 'unidade'),
  ('Atadura de crepom 15 cm',                       'Material médico-hospitalar', 'unidade'),
  ('Atadura de crepom 20 cm',                       'Material médico-hospitalar', 'unidade'),
  ('Compressa de gaze estéril 7,5x7,5 — pacote',    'Material médico-hospitalar', 'pacote'),
  ('Gaze não estéril — pacote 500',                 'Material médico-hospitalar', 'pacote'),
  ('Compressa cirúrgica 25x28',                     'Material médico-hospitalar', 'unidade'),
  ('Algodão hidrófilo 500 g — rolo',                'Material médico-hospitalar', 'rolo'),
  ('Esparadrapo 10 cm x 4,5 m',                     'Material médico-hospitalar', 'rolo'),
  ('Fita microporosa 2,5 cm',                       'Material médico-hospitalar', 'rolo'),
  ('Fita microporosa 5 cm',                         'Material médico-hospitalar', 'rolo'),
  ('Curativo transparente estéril',                 'Material médico-hospitalar', 'unidade'),
  ('Lâmina de bisturi nº 11',                       'Material médico-hospitalar', 'unidade'),
  ('Lâmina de bisturi nº 15',                       'Material médico-hospitalar', 'unidade'),
  ('Lâmina de bisturi nº 23',                       'Material médico-hospitalar', 'unidade'),
  ('Fio de sutura nylon 2-0',                       'Material médico-hospitalar', 'unidade'),
  ('Fio de sutura nylon 3-0',                       'Material médico-hospitalar', 'unidade'),
  ('Fio de sutura nylon 4-0',                       'Material médico-hospitalar', 'unidade'),
  ('Eletrodo para ECG — pacote 50',                 'Material médico-hospitalar', 'pacote'),
  ('Gel condutor 100 g',                            'Material médico-hospitalar', 'frasco'),
  ('Abaixador de língua — pacote 100',              'Material médico-hospitalar', 'pacote'),
  ('Máscara de nebulização adulto',                 'Material médico-hospitalar', 'unidade'),
  ('Máscara de nebulização infantil',               'Material médico-hospitalar', 'unidade'),
  ('Cateter nasal de O2 (óculos)',                  'Material médico-hospitalar', 'unidade'),
  ('Umidificador de O2 com frasco',                 'Material médico-hospitalar', 'unidade'),
  ('Swab de álcool 70% — caixa 100',                'Material médico-hospitalar', 'caixa'),
  ('Termômetro clínico digital',                    'Material médico-hospitalar', 'unidade'),
  -- EPI
  ('Máscara cirúrgica tripla — caixa 50',           'EPI', 'caixa'),
  ('Máscara N95 / PFF2',                            'EPI', 'unidade'),
  ('Avental descartável manga longa',               'EPI', 'unidade'),
  ('Avental impermeável',                           'EPI', 'unidade'),
  ('Touca descartável — pacote 100',                'EPI', 'pacote'),
  ('Propé descartável — par',                       'EPI', 'par'),
  ('Óculos de proteção',                            'EPI', 'unidade'),
  ('Protetor facial (face shield)',                 'EPI', 'unidade'),
  ('Luva nitrílica — caixa 100',                    'EPI', 'caixa'),
  -- Higiene e limpeza
  ('Álcool 70% — 1 L',                              'Higiene e limpeza', 'frasco'),
  ('Álcool gel 70% — 500 mL',                       'Higiene e limpeza', 'frasco'),
  ('Sabonete líquido — galão 5 L',                  'Higiene e limpeza', 'galão'),
  ('Clorexidina degermante 2% — 1 L',               'Higiene e limpeza', 'frasco'),
  ('Clorexidina alcoólica 0,5% — 1 L',              'Higiene e limpeza', 'frasco'),
  ('Hipoclorito de sódio 1% — 1 L',                 'Higiene e limpeza', 'frasco'),
  ('Desinfetante hospitalar — galão 5 L',           'Higiene e limpeza', 'galão'),
  ('Saco de lixo comum 100 L — pacote 100',         'Higiene e limpeza', 'pacote'),
  ('Saco de lixo infectante branco 100 L — pct',    'Higiene e limpeza', 'pacote'),
  ('Papel toalha interfolha — pacote 1000',         'Higiene e limpeza', 'pacote'),
  ('Papel higiênico rolão — fardo 8',               'Higiene e limpeza', 'pacote'),
  ('Pano multiuso — pacote',                        'Higiene e limpeza', 'pacote'),
  -- Escritório e expediente
  ('Papel A4 — resma 500',                          'Escritório e expediente', 'resma'),
  ('Caneta esferográfica azul',                     'Escritório e expediente', 'unidade'),
  ('Caneta esferográfica preta',                    'Escritório e expediente', 'unidade'),
  ('Caneta esferográfica vermelha',                 'Escritório e expediente', 'unidade'),
  ('Grampo 26/6 — caixa 5000',                      'Escritório e expediente', 'caixa'),
  ('Clips 2/0 — caixa 100',                         'Escritório e expediente', 'caixa'),
  ('Pasta AZ',                                      'Escritório e expediente', 'unidade'),
  ('Envelope A4',                                   'Escritório e expediente', 'unidade'),
  ('Etiqueta adesiva — rolo',                       'Escritório e expediente', 'rolo'),
  ('Pilha AA — par',                                'Escritório e expediente', 'par'),
  ('Pilha AAA — par',                               'Escritório e expediente', 'par'),
  -- Impressos e formulários
  ('Capa de prontuário',                            'Impressos e formulários', 'unidade'),
  ('Folha de evolução clínica — bloco',             'Impressos e formulários', 'pacote'),
  ('Folha de prescrição médica — bloco',            'Impressos e formulários', 'pacote'),
  ('Ficha de atendimento PS — bloco',               'Impressos e formulários', 'pacote'),
  ('Pulseira de identificação do paciente',         'Impressos e formulários', 'unidade'),
  ('Receituário comum — bloco',                     'Impressos e formulários', 'pacote'),
  -- Rouparia e enxoval
  ('Lençol solteiro',                               'Rouparia e enxoval', 'unidade'),
  ('Fronha',                                        'Rouparia e enxoval', 'unidade'),
  ('Cobertor',                                      'Rouparia e enxoval', 'unidade'),
  ('Toalha de banho',                               'Rouparia e enxoval', 'unidade'),
  ('Camisola de paciente',                          'Rouparia e enxoval', 'unidade'),
  ('Campo cirúrgico simples',                       'Rouparia e enxoval', 'unidade'),
  -- Nutrição e copa
  ('Copo descartável 200 mL — pacote 100',          'Nutrição e copa', 'pacote'),
  ('Copo descartável 50 mL — pacote 100',           'Nutrição e copa', 'pacote'),
  ('Colher descartável — pacote 100',               'Nutrição e copa', 'pacote'),
  ('Guardanapo — pacote',                           'Nutrição e copa', 'pacote'),
  ('Filtro de café nº 103 — caixa 30',              'Nutrição e copa', 'caixa'),
  -- Manutenção predial
  ('Lâmpada LED tubular',                           'Manutenção predial', 'unidade'),
  ('Fita isolante — rolo',                          'Manutenção predial', 'rolo'),
  ('Tomada / plugue',                               'Manutenção predial', 'unidade'),
  ('Bateria 9 V',                                   'Manutenção predial', 'unidade'),
  ('Cadeado',                                       'Manutenção predial', 'unidade'),
  -- Informática
  ('Toner de impressora (modelo padrão)',           'Informática', 'unidade'),
  ('Mouse USB',                                     'Informática', 'unidade'),
  ('Teclado USB',                                   'Informática', 'unidade'),
  ('Cabo de rede montado 2 m',                      'Informática', 'unidade'),
  -- Laboratório
  ('Tubo de coleta EDTA (tampa roxa)',              'Laboratório', 'unidade'),
  ('Tubo de coleta soro (tampa amarela)',           'Laboratório', 'unidade'),
  ('Agulha para coleta a vácuo',                    'Laboratório', 'unidade'),
  ('Lanceta descartável',                           'Laboratório', 'unidade'),
  ('Frasco de urina estéril',                       'Laboratório', 'unidade')
) as v(nome, categoria, unidade)
where not exists (
  select 1 from public.sup_itens s
   where lower(s.nome) = lower(v.nome)
);

-- Verificação: total por categoria
select categoria, count(*) as itens
  from public.sup_itens
 group by categoria
 order by categoria;
